// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFRd-cW7KqXscjt6mHh9eSZT404cuO7S0',
    appId: '1:35186003403:android:5a0f87f673788d45917a4e',
    messagingSenderId: '35186003403',
    projectId: 'facedetectionbyfirebaseml',
    storageBucket: 'facedetectionbyfirebaseml.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUAXB5Ry0vvXQCtWZ2TMenVgeSGQThcRE',
    appId: '1:35186003403:ios:075628f94ace4569917a4e',
    messagingSenderId: '35186003403',
    projectId: 'facedetectionbyfirebaseml',
    storageBucket: 'facedetectionbyfirebaseml.appspot.com',
    iosClientId: '35186003403-uilrfj11j1oaj5msocg2j45332f66lcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.faceDetectionByFirebaseMl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUAXB5Ry0vvXQCtWZ2TMenVgeSGQThcRE',
    appId: '1:35186003403:ios:075628f94ace4569917a4e',
    messagingSenderId: '35186003403',
    projectId: 'facedetectionbyfirebaseml',
    storageBucket: 'facedetectionbyfirebaseml.appspot.com',
    iosClientId: '35186003403-uilrfj11j1oaj5msocg2j45332f66lcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.faceDetectionByFirebaseMl',
  );
}
